[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
via_ir = true
ffi = true
solc_version = "0.8.28" # Set default to highest needed version
optimizer_runs = 200


remappings = [
    '@forge-std/=lib/forge-std/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/',
]


[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/9SQ4az7o0p6zxDpbFuaj2"

[profile.sepolia]
private_key = "0x86b0273c51033f5aea63b4e11c8b69f260270d729b2d86fe7b79acd07bf17f59"



etherscan_api_key ="TCJ3I9YEYK14YJV3TU7GECGIN7F1M9XS3F"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

ignored_error_codes = [5740]
ignored_warnings_from = ["src/KryptoSignatures.sol"]
